config/routes.rb
Rails.application.routes.draw do
	root to: 'surveys#index'

  	resources :surveys do
  		collection do
  			get :export
  			get :search
  		end
  	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
	require 'axlsx'
	include PgSearch

	has_many :up_vehicle_stats, -> { where type: :up }, class_name: 'VehicleStat', dependent: :destroy
	has_many :down_vehicle_stats, -> { where type: :down }, class_name: 'VehicleStat', dependent: :destroy

	validates_presence_of :date, :district, :road_name, :from, :to, :road_class, :road_type, :no_of_lanes

	pg_search_scope :search, against: [:survey_ref, :road_name, :from, :to]

end

app/models/vehicle_stat.rb
class VehicleStat < ApplicationRecord
	require 'roo'
 	self.inheritance_column = "_type"

  default_scope { order(id: :asc) }

 	belongs_to :survey

	def self.import(survey, file)
	  spreadsheet = open_spreadsheet(file)	    

	  survey.up_vehicle_stats.destroy_all
	  survey.down_vehicle_stats.destroy_all
	  (1..2).each do |sheet_no|
	  	sheet = spreadsheet.sheet("Data_#{sheet_no}")	  	

		  (6..85).each do |row_no|
		  	time = sheet.excelx_value(row_no, 1).gsub(".", ":").split("-")
	 			counts = sheet.row(row_no)[1, 14].map(&:to_i)
        total = sheet.excelx_value(row_no, 16).to_i 

	 			if (time[1].to_time - time[0].to_time)/1.minute == 15.0
			  	data = {
			  		from: time[0],
			  		to: time[1],
			  		total: total > 0 ? total : counts.sum
			  	}	  	

			  	counts_hash = Hash[VehicleStat.column_names[5, 14].zip counts]
			  	data = data.merge(counts_hash)

			  	if sheet_no == 1
						survey.up_vehicle_stats.create(data)
			  	elsif sheet_no == 2
			  		survey.down_vehicle_stats.create(data)
			  	end  	
			  end	  	

		  end
		end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)	  
	  when ".xlsx" 
	  	then Roo::Excelx.new(file.path)
	  else 
	  	raise "Unknown file type: #{file.original_filename}"
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.paginate(:page => params[:page], :per_page => params[:per_page] || 20)
  end

  def search
    @surveys = Survey.all
    if params[:q].present?
      @surveys = @surveys.search(params[:q])
    end
    if params[:date_from].present?
      @surveys = @surveys.where("date >= ?", params[:from])
    end
    if params[:date_to].present?
      @surveys = @surveys.where("date <= ?", params[:to])
    end    
    if params[:district].present?
      @surveys = @surveys.where(district: params[:district])
    end
    if params[:road_class].present?
      @surveys = @surveys.where(road_class: params[:road_class])
    end
    if params[:road_type].present?
      @surveys = @surveys.where(road_type: params[:road_type])
    end
    if params[:no_of_lanes].present?
      @surveys = @surveys.where(no_of_lanes: params[:no_of_lanes])
    end
    if params[:lane_width_from].present?
      @surveys = @surveys.where("lane_width >= ?", params[:lane_width_from])
    end
    if params[:lane_width_to].present?
      @surveys = @surveys.where("lane_width <= ?", params[:lane_width_to])
    end 
    if params[:shoulder_type].present?
      @surveys = @surveys.where(shoulder_type: params[:shoulder_type])
    end
    if params[:shoulder_width_from].present?
      @surveys = @surveys.where("shoulder_width >= ?", params[:shoulder_width_from])
    end
    if params[:shoulder_width_to].present?
        @surveys = @surveys.where("shoulder_width <= ?", params[:shoulder_width_to])
    end 
    if params[:pavement_condition].present?
      @surveys = @surveys.where(pavement_condition: params[:pavement_condition])
    end
    if params[:built_environment].present?
      @surveys = @surveys.where(built_environment: params[:built_environment])
    end
    if params[:row_from].present?
      @surveys = @surveys.where("row >= ?", params[:row_from])
    end
    if params[:row_to].present?
      @surveys = @surveys.where("row <= ?", params[:row_to])
    end
    if params[:speed_limit].present?
      @surveys = @surveys.where(speed_limit: params[:speed_limit])
    end
    if params[:ffs_from].present?
      @surveys = @surveys.where("ffs >= ?", params[:ffs_from])
    end
    if params[:ffs_to].present?
      @surveys = @surveys.where("ffs <= ?", params[:ffs_to])
    end
    if params[:traffic_composition].present?
      @surveys = @surveys.where(traffic_composition: params[:traffic_composition])
    end
    if params[:access_point_density].present?
      @surveys = @surveys.where(access_point_density: params[:access_point_density])
    end
  end
  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save 
        VehicleStat.import(@survey, params[:survey][:vehicle_stat]) if params[:survey][:vehicle_stat]
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def export
    @surveys = Survey.find(params[:survey_ids])
    respond_to do |format|
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="vehicle_stats.xlsx"'
      }
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        VehicleStat.import(@survey, params[:survey][:vehicle_stat]) if params[:survey][:vehicle_stat]
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:survey_ref, :date, :district, :road_name, :from, :to, :latitude, :longitude, :road_class, :road_type, :no_of_lanes, :lane_width, 
        :shoulder_type, :shoulder_width, :pavement_condition, :built_environment, :row, :speed_limit, :ffs, :traffic_composition, :access_point_density, :up_grade, 
        :up_distance_to_junction, :up_junction_type, :up_signalized, :down_grade, :down_distance_to_junction, :down_junction_type, :down_signalized)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TrafficStats" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TrafficStats</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Surveys List", "/surveys"  %></li>
            <li><%= link_to "Search", "/surveys/search"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/surveys/edit.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/surveys/index.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <%= link_to t('.new', :default => "Create New"), new_survey_path, :class => 'btn btn-default create_new_button' %><br><br><br><br>
  <%= page_entries_info @surveys %><br><br>
</div>
  

<%= form_tag(export_surveys_path(format: "xlsx"), :method => "get", id: "export_form") do %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:survey_ref) %></th>
        <th><%= model_class.human_attribute_name(:date) %></th>
        <th><%= model_class.human_attribute_name(:district) %></th>
        <th><%= model_class.human_attribute_name(:road_name) %></th>
        <th><%= model_class.human_attribute_name(:from) %></th>
        <th><%= model_class.human_attribute_name(:to) %></th>
        <th><%= model_class.human_attribute_name(:road_class) %></th>
        <th><%= model_class.human_attribute_name(:road_type) %></th>      
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @surveys.each do |survey| %>
        <tr>
          <td><%= link_to survey.id, survey_path(survey) %></td>
          <td><%= survey.survey_ref %></td>
          <td><%= survey.date %></td>
          <td><%= survey.district.humanize %></td>
          <td><%= survey.road_name %></td>
          <td><%= survey.from %></td>
          <td><%= survey.to %></td>
          <td><%= survey.road_class %></td>
          <td><%= survey.road_type.humanize %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        survey_path(survey), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_survey_path(survey), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        survey_path(survey),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 
  <%= will_paginate @surveys %>
<% end %>

app/views/surveys/new.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/surveys/search.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <%= form_tag(search_surveys_path, :method => "get", id: "search_form") do %>
    <div class="form-group">
      <h4>Search</h4>
      <div class="row">
        <div class="col-md-3"><%= text_field_tag :q, params[:q], class: 'form-control' %></div>
      </div>
    </div>
    
    <h4>Filters</h4>
    <div class="form-group">  

      <%= label_tag nil, "Date Range" %>
      <div class="row">
        <div class="col-md-2"><%= text_field_tag :date_from, params[:from], :class => 'form-control date_select' %></div>
        <div class="col-md-2"><%= text_field_tag :date_to, params[:to], :class => 'form-control date_select' %></div>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag :district, nil %>  
      <%= select_tag :district, options_for_select(["Ampara", "Anuradhapura", "Badulla", "Batticaloa", "Colombo", "Galle", "Gampaha", "Hambantota", "Jaffna", "Kalutara""Kandy", "Kegalle", "Kilinochchi", "Kurunegala", "Mannar", "Matale", "Matara", "Moneragala", "Mullaitivu", "Nuwara Eliya", "Polonnaruwa", "Puttalam", "Ratnapura", "Trincomalee", "Vavuniya"].collect { |o| 
      [ o, o.parameterize.underscore ] }, (params[:district])), {include_blank: true, class: 'form-control'} %>
    </div>   

    <div class="form-group">
      <%= label_tag :road_class, nil %>     
      <%= select_tag :road_class, options_for_select(["AA", "AB", "AC", "B", "C", "D", "E", "Other"], (params[:road_class])), {include_blank: true, :class => 'form-control'} %>
    </div> 

    <div class="form-group">
      <%= label_tag :road_type, nil %>     
      <%= select_tag :road_type, options_for_select(["Undivided", "Divided", "Median seperated", "One way"].collect { |o| 
      [ o, o.parameterize.underscore ] }, (params[:road_type])), {include_blank: true, :class => 'form-control'} %>
    </div> 

    <div class="form-group">
      <%= label_tag :no_of_lanes, nil %>     
      <%= select_tag :no_of_lanes, options_for_select([1, 2, 3, 4], params[:no_of_lanes]), {include_blank: true, :class => 'form-control'} %>
    </div> 

    <div class="form-group">
      <%= label_tag nil, "Lane Width Range (m)" %>
      <div class="row">
        <div class="col-md-1"><%= text_field_tag :lane_width_from, params[:lane_width_from], :class => 'form-control' %></div>
        <div class="col-md-1"><%= text_field_tag :lane_width_to, params[:lane_width_to], :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :shoulder_type, nil %>     
      <%= select_tag :shoulder_type, options_for_select(["Undivided", "Divided", "Median seperated", "One way"].collect { |o| 
        [ o, o.parameterize.underscore ] }, (params[:shoulder_type])), {include_blank: true, :class => 'form-control'} %>
    </div>

    <div class="form-group">
      <%= label_tag nil, "Shoulder Width Range (m)" %>
      <div class="row">
        <div class="col-md-1"><%= text_field_tag :shoulder_width_from, params[:shoulder_width_from], :class => 'form-control' %></div>
        <div class="col-md-1"><%= text_field_tag :shoulder_width_to, params[:shoulder_width_to], :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :pavement_condition, nil %> 
      <%= select_tag :pavement_condition, options_for_select(["Good", "Average", "Poor", "One way"].collect { |o| 
        [ o, o.parameterize.underscore ] }, (params[:pavement_condition])), {include_blank: true, :class => 'form-control'} %>
    </div>

    <div class="form-group">
      <%= label_tag :built_environment%> 
      <%= select_tag :built_environment, options_for_select(["Urban", "Sub urban", "Rural"].collect { |o| 
        [ o, o.parameterize.underscore ] }, (params[:built_environment])), {include_blank: true, :class => 'form-control'} %> 
    </div>

    <div class="form-group">
      <%= label_tag nil, "ROW Range" %>
      <div class="row">
        <div class="col-md-1"><%= text_field_tag :row_from, params[:row_from], :class => 'form-control' %></div>
        <div class="col-md-1"><%= text_field_tag :row_to, params[:row_to], :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :speed_limit %>
      <%= select_tag :speed_limit, options_for_select([70, 60, 50, 40], params[:speed_limit]), {include_blank: true, :class => 'form-control'} %> 
    </div>

    <div class="form-group">
      <%= label_tag nil, "FFS Range" %>
      <div class="row">
        <div class="col-md-1"><%= text_field_tag :ffs_from, params[:ffs_from], :class => 'form-control' %></div>
        <div class="col-md-1"><%= text_field_tag :ffs_to, params[:ffs_to], :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :traffic_composition %> 
      <%= select_tag :traffic_composition, options_for_select(["Type 1", "Type 2", "Type 3", "Type 4", "Type 5"].collect { |o| 
        [ o, o.parameterize.underscore ] }, (params[:traffic_composition])), {include_blank: true, :class => 'form-control'} %>
    </div>    
  
    <div class="form-group">
      <%= label_tag :access_point_density %> 
      <%= select_tag :access_point_density, options_for_select(["High", "Medium", "Low"].collect { |o| 
        [ o, o.parameterize.underscore ] }, (params[:access_point_density])), {include_blank: true, :class => 'form-control'} %>
    </div>

    <div class="form-group">
      <%= submit_tag "Search", :name => nil, class: "btn" %>
    </div> 
  <% end %>
  <br>
  <br>
</div>

<%= form_tag(export_surveys_path(format: "xlsx"), :method => "get", id: "export_form") do %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:survey_ref) %></th>
        <th><%= model_class.human_attribute_name(:date) %></th>
        <th><%= model_class.human_attribute_name(:district) %></th>
        <th><%= model_class.human_attribute_name(:road_name) %></th>
        <th><%= model_class.human_attribute_name(:from) %></th>
        <th><%= model_class.human_attribute_name(:to) %></th>
        <th><%= model_class.human_attribute_name(:road_class) %></th>
        <th><%= model_class.human_attribute_name(:road_type) %></th>      
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @surveys.each do |survey| %>
        <tr>
          <td><%= check_box_tag 'survey_ids[]', survey.id, false %></td>
          <td><%= link_to survey.id, survey_path(survey) %></td>
          <td><%= survey.survey_ref %></td>
          <td><%= survey.date %></td>
          <td><%= survey.district.humanize %></td>
          <td><%= survey.road_name %></td>
          <td><%= survey.from %></td>
          <td><%= survey.to %></td>
          <td><%= survey.road_class %></td>
          <td><%= survey.road_type.humanize %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        survey_path(survey), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_survey_path(survey), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        survey_path(survey),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 

  <br><br>
  <%= submit_tag "Download", class: "btn", data: { disable_with: false } %>
<% end %>

app/views/surveys/show.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:survey_ref) %>:</strong></dt>
  <dd><%= @survey.survey_ref %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @survey.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:district) %>:</strong></dt>
  <dd><%= @survey.district.try(:humanize)%></dd>
  <dt><strong><%= model_class.human_attribute_name(:road_name) %>:</strong></dt>
  <dd><%= @survey.road_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:from) %>:</strong></dt>
  <dd><%= @survey.from %></dd>
  <dt><strong><%= model_class.human_attribute_name(:to) %>:</strong></dt>
  <dd><%= @survey.to %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @survey.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @survey.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:road_class) %>:</strong></dt>
  <dd><%= @survey.road_class %></dd>
  <dt><strong><%= model_class.human_attribute_name(:road_type) %>:</strong></dt>
  <dd><%= @survey.road_type.try(:humanize) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:no_of_lanes) %>:</strong></dt>
  <dd><%= @survey.no_of_lanes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lane_width) %>:</strong></dt>
  <dd><%= @survey.lane_width %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shoulder_type) %>:</strong></dt>
  <dd><%= @survey.shoulder_type.try(:humanize) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shoulder_width) %>:</strong></dt>
  <dd><%= @survey.shoulder_width %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pavement_condition) %>:</strong></dt>
  <dd><%= @survey.pavement_condition.try(:humanize) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:built_environment) %>:</strong></dt>
  <dd><%= @survey.built_environment.try(:humanize) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:row).upcase %>:</strong></dt>
  <dd><%= @survey.row %></dd>
  <dt><strong><%= model_class.human_attribute_name(:speed_limit) %>:</strong></dt>
  <dd><%= @survey.speed_limit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ffs).upcase %>:</strong></dt>
  <dd><%= @survey.ffs %></dd>
  <dt><strong><%= model_class.human_attribute_name(:traffic_composition) %>:</strong></dt>
  <dd><%= @survey.traffic_composition.try(:humanize) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:access_point_density) %>:</strong></dt>
  <dd><%= @survey.access_point_density.try(:humanize) %></dd>

  <br>
  <h4>Direction 1</h4>
  <dt><strong>Grade:</strong></dt>
  <dd><%= @survey.up_grade.try(:humanize)  %></dd>
  <dt><strong>Distance to junction (km):</strong></dt>
  <dd><%= @survey.up_distance_to_junction %></dd>
  <dt><strong>Junction type:</strong></dt>
  <dd><%= @survey.up_junction_type.humanize %></dd>
  <dt><strong>Signalized:</strong></dt>
  <dd><%= @survey.up_signalized ? "Yes" : "No" unless @survey.up_signalized.nil? %></dd>

  <h4>Direction 2</h4>
  <dt><strong>Grade:</strong></dt>
  <dd><%= @survey.down_grade.try(:humanize)  %></dd>
  <dt><strong>Distance to junction (km):</strong></dt>
  <dd><%= @survey.down_distance_to_junction %></dd>
  <dt><strong>Junction type:</strong></dt>
  <dd><%= @survey.down_junction_type.humanize %></dd>
  <dt><strong>Signalized:</strong></dt>
  <dd><%= @survey.down_signalized ? "Yes" : "No" unless @survey.down_signalized.nil? %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              surveys_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_survey_path(@survey), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              survey_path(@survey),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>